### ISSUE TITLE
[Crawler Stopped]

### ISSUE THREAD

**Issue by valamidev** [ethereum/discv4-dns-lists#9]
I just noticed that the list is not updated since a week, is the project stopped or just temporary having issues?

Btw. big kudos for this repository, I hope it will kept alive.

**Comment by imom0** [comment]
It seems the service is currently down. I want to express my appreciation for the importance of the data that this project provides. It is an essential resource for developers and users of the Ethereum network. I hope that the service will be restored as soon as possible.

**Comment by BBBonnie** [comment]
please restore the service asap if it's possible. Thank you for making this project public and it has been very useful :))

**Comment by imom0** [comment]
@fjl

**Comment by fjl** [comment]
Hi guys! We are working on restoring service. However, please note that we are not committed to providing this repository forever. The size of the repo is steadily increasing and it will no longer be feasible to store it in GitHub at some point. If you require access to this data, you can run a crawler yourself. It is not complicated to do that.

**Comment by BBBonnie** [comment]
@fjl Understood. Could you please guide us on how to run a crawler? thank you.

**Comment by holiman** [comment]
It is running again, we'll try to monitor it better. 
As for running these yourself, there's more info here: https://github.com/ethereum/discv4-crawl
